global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vintage-community-app'
    static_configs:
      - targets: ['app-blue:8080', 'app-green:8081']
